---
# The default connectivity variables are below. This playbook assumes that all
# network modules support the 'network_cli' connection method; those that do
# not can use the legacy provider credentials below with 'local' connection.
ansible_connection: "network_cli"
ansible_user: "cisco"
ansible_password: "cisco"
ansible_network_os: "ios"
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: cisco
os: ios


snmp_servers:
  - 10.1.1.1
  - 10.2.1.1

users:
  admin: cisco!123
  cisco: cisco

ntp_servers:
  - 172.20.1.1
  - 172.20.2.1
  - 172.20.3.1  