[all:vars]

[cisco]
isr01 ansible_host=10.122.188.75
sw01 ansible_host=10.82.139.162

#isr01 ansible_host=10.122.188.75
#asr01 ansible_host=10.122.188.78
#3850-1 ansible_host=10.122.188.78
#3850-2 ansible_host=10.122.188.78

[cisco:vars]
ansible_user=cisco
ansible_password=cisco
ansible_network_os=ios
ansible_ssh_pass=cisco